<?php if (isset($flash['success'])): ?>
    <div class="alert alert-success" role="alert">
        <?= $flash['success'][0] ?>
    </div>
<?php endif; ?>

<?php if (isset($flash['error'])): ?>
    <div class="alert alert-danger" role="alert">
        <?= $flash['error'][0] ?>
    </div>
<?php endif; ?>

<h1>Сайт: <?= htmlspecialchars($url['name']) ?></h1>

<form action="/urls/<?= $url['id'] ?>/checks" method="post">
    <button type="submit" class="btn btn-primary">Проверить</button>
</form>

<h2 class="mt-5 mb-3">Проверки</h2>

<div class="table-responsive">
    <table class="table table-bordered table-hover text-nowrap">
        <thead>
            <tr>
                <th>ID</th>
                <th>Код ответа</th>
                <th>h1</th>
                <th>title</th>
                <th>description</th>
                <th>keywords</th>
                <th>Дата проверки</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($checks as $check): ?>
                <tr>
                    <td><?= htmlspecialchars($check['id']) ?></td>
                    <td><?= htmlspecialchars($check['status_code']) ?></td>
                    <td><?= htmlspecialchars($check['h1']) ?></td>
                    <td></td>
                    <td><?= htmlspecialchars($check['description']) ?></td>
                    <td><?= htmlspecialchars($check['keywords']) ?></td>
                    <td><?= $check['created_at'] ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div> 