<?php include 'flash.phtml'; ?>

<h1>Сайты</h1>

<div class="table-responsive">
    <table class="table table-bordered table-hover text-nowrap">
        <thead>
            <tr>
                <th>ID</th>
                <th>Имя</th>
                <th>Последняя проверка</th>
                <th>Код ответа</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($urls as $url): ?>
                <tr>
                    <td><?= htmlspecialchars($url['id']) ?></td>
                    <td>
                        <a href="/urls/<?= $url['id'] ?>">
                            <?= htmlspecialchars($url['name']) ?>
                        </a>
                    </td>
                    <td><?= $url['last_check_at'] ? date('Y-m-d H:i:s', strtotime($url['last_check_at'])) : '' ?></td>
                    <td><?= $url['last_status_code'] ?? '' ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div> 